
_localeString = {
	"it": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'vanilla birthday',
    '%4'                    : 'bubblegum pink',
    '%8'                    : 'sunshine vanilla',
    '%16'                   : 'valrhona blonde ganache',
    '%32'                   : 'chocolare peanut butter cheesecake',
    '%64'                   : 'chocolate mint fudge',
    '%128'                  : 'chocolate spider web',
    '%256'                  : 'toasted marshmallow',
    '%512'                  : 'cookies and creme',
    '%1024'                 : 'chocolate sundae',
    '%2048'                 : 'white chocolate peppermint',
    '%4096'                 : '2017 Confetti Vanilla',
    '%8192'                 : 'Rainbow',
    '%p0'                   : 'vanilla birthday',
    '%p4'                   : 'bubblegum pink',
    '%p8'                   : 'sunshine vanilla',
    '%p16'                  : 'valrhona blonde ganache',
    '%p32'                  : 'choc. peanut butter cheesecake',
    '%p64'                  : 'choc. mint fudge',
    '%p128'                 : 'choc. spider web',
    '%p256'                 : 'toasted marshmallow',
    '%p512'                 : 'cookies and creme',
    '%p1024'                : 'choc. sundae',
    '%p2048'                : 'white choc. peppermint',
    '%p4096'                : '2017 Confetti Vanilla',
    '%p8192'                : 'Rainbow'

	},

  "en": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'vanilla birthday',
    '%4'                    : 'bubblegum pink',
    '%8'                    : 'sunshine vanilla',
    '%16'                   : 'valrhona blonde ganache',
    '%32'                   : 'chocolare peanut butter cheesecake',
    '%64'                   : 'chocolate mint fudge',
    '%128'                  : 'chocolate spider web',
    '%256'                  : 'toasted marshmallow',
    '%512'                  : 'cookies and creme',
    '%1024'                 : 'chocolate sundae',
    '%2048'                 : 'white chocolate peppermint',
    '%4096'                 : '2017 Confetti Vanilla',
    '%8192'                 : 'Rainbow',
    '%p0'                   : 'vanilla birthday',
    '%p4'                   : 'bubblegum pink',
    '%p8'                   : 'sunshine vanilla',
    '%p16'                  : 'valrhona blonde ganache',
    '%p32'                  : 'choc. peanut butter cheesecake',
    '%p64'                  : 'choc. mint fudge',
    '%p128'                 : 'choc. spider web',
    '%p256'                 : 'toasted marshmallow',
    '%p512'                 : 'cookies and creme',
    '%p1024'                : 'choc. sundae',
    '%p2048'                : 'white choc. peppermint',
    '%p4096'                : '2017 Confetti Vanilla',
    '%p8192'                : 'Rainbow'
  },

  "zh": {
    "%game-intro"           : "加入<strong>纸杯蛋糕!</strong>",
    "%restart-button"       : "重新开始",
    "%keep-playing-button"  : "继续游戏",
    "%retry-button"         : "重试",
    "%game-won"             : "你赢了！",
    "%game-over"            : "游戏结束！",
    "%game-explanation"     : "<strong class=\"important\">游戏玩法：</strong>使用<strong>方向键</strong>移动方块。当两个相同图案的方块相碰时，它们会<strong>升级！</strong>",
    "%disclaimer"           : "",
    "%credits"              : "纸杯蛋糕图片来自<a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a >。",
    "%tweet1"               : "我在2048-纸杯蛋糕中得到了\"",
    "%tweet2"               : "分 #2048game",
    "%tile-legend"          : "<strong class=\"important\">方块图例：</strong>",
    '%2'                    : '香草生日蛋糕',
    '%4'                    : '泡泡糖粉',
    '%8'                    : '阳光香草',
    '%16'                   : '法芙娜金巧克力淋面',
    '%32'                   : '巧克力花生酱芝士蛋糕',
    '%64'                   : '巧克力薄荷软糖',
    '%128'                  : '巧克力蜘蛛网',
    '%256'                  : '烤棉花糖',
    '%512'                  : '奥利奥奶油',
    '%1024'                 : '巧克力圣代',
    '%2048'                 : '白巧克力薄荷',
    '%4096'                 : '2017彩虹香草',
    '%8192'                 : '彩虹',
    '%p0'                   : '香草生日蛋糕',
    '%p4'                   : '泡泡糖粉',
    '%p8'                   : '阳光香草',
    '%p16'                  : '法芙娜金巧克力淋面',
    '%p32'                  : '巧克力花生酱芝士蛋糕',
    '%p64'                  : '巧克力薄荷软糖',
    '%p128'                 : '巧克力蜘蛛网',
    '%p256'                 : '烤棉花糖',
    '%p512'                 : '奥利奥奶油',
    '%p1024'                : '巧克力圣代',
    '%p2048'                : '白巧克力薄荷',
    '%p4096'                : '2017彩虹香草',
    '%p8192'                : '彩虹'
  },

  "ja": {
    "%game-intro": "<strong>カップケーキ</strong>に参加しよう！",
    "%restart-button": "もう一度プレイ",
    "%keep-playing-button": "続ける",
    "%retry-button": "リトライ",
    "%game-won": "あなたの勝ち！",
    "%game-over": "ゲームオーバー！",
    "%game-explanation": "<strong class=\"important\">遊び方：</strong><strong>矢印キー</strong>でタイルを動かします。同じ絵柄のタイルが合体すると<strong>昇格</strong>します！",
    "%disclaimer": "",
    "%credits": "カップケーキ画像：<a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>。",
    "%tweet1": "2048-カップケーキで\"",
    "%tweet2": "点を獲得 #2048game",
    "%tile-legend": "<strong class=\"important\">タイルの説明：</strong>",
    '%2': 'バニラバースデー',
    '%4': 'バブルガムピンク',
    '%8': 'サンシャインバニラ',
    '%16': 'ヴァローナブロンドガナッシュ',
    '%32': 'チョコピーナッツバターチーズケーキ',
    '%64': 'チョコミントファッジ',
    '%128': 'チョコレートスパイダーウェブ',
    '%256': 'トーストマシュマロ',
    '%512': 'クッキー＆クリーム',
    '%1024': 'チョコレートサンデー',
    '%2048': 'ホワイトチョコミント',
    '%4096': '2017コンフェッティバニラ',
    '%8192': 'レインボー',
    '%p0': 'バニラバースデー',
    '%p4': 'バブルガムピンク',
    '%p8': 'サンシャインバニラ',
    '%p16': 'ヴァローナブロンドガナッシュ',
    '%p32': 'チョコピーナッツバターチーズケーキ',
    '%p64': 'チョコミントファッジ',
    '%p128': 'チョコレートスパイダーウェブ',
    '%p256': 'トーストマシュマロ',
    '%p512': 'クッキー＆クリーム',
    '%p1024': 'チョコレートサンデー',
    '%p2048': 'ホワイトチョコミント',
    '%p4096': '2017コンフェッティバニラ',
    '%p8192': 'レインボー'
  },

  "de": {
    "%game-intro": "Schließe dich den <strong>Cupcakes!</strong> an",
    "%restart-button": "Nochmal spielen",
    "%keep-playing-button": "Weiterspielen",
    "%retry-button": "Wiederholen",
    "%game-won": "Du hast gewonnen!",
    "%game-over": "Spiel vorbei!",
    "%game-explanation": "<strong class=\"important\">So wird gespielt:</strong> Benutze die <strong>Pfeiltasten</strong>, um die Kacheln zu bewegen. Wenn zwei Kacheln mit dem gleichen Symbol sich berühren, <strong>werden sie befördert!</strong>",
    "%disclaimer": "",
    "%credits": "Cupcake-Bilder von <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1": "Ich habe \"",
    "%tweet2": " bei 2048-CUPCAKES erzielt #2048game",
    "%tile-legend": "<strong class=\"important\">Kachel-Legende:</strong>",
    '%2': 'Vanille-Geburtstag',
    '%4': 'Bubblegum Pink',
    '%8': 'Sonnenschein Vanille',
    '%16': 'Valrhona Blonde Ganache',
    '%32': 'Schoko-Erdnussbutter-Käsekuchen',
    '%64': 'Schoko-Minze Fudge',
    '%128': 'Schoko-Spinnennetz',
    '%256': 'Geröstetes Marshmallow',
    '%512': 'Kekse & Creme',
    '%1024': 'Schoko-Sundae',
    '%2048': 'Weiße Schoko-Pfefferminze',
    '%4096': '2017 Konfetti Vanille',
    '%8192': 'Regenbogen',
    '%p0': 'Vanille-Geburtstag',
    '%p4': 'Bubblegum Pink',
    '%p8': 'Sonnenschein Vanille',
    '%p16': 'Valrhona Blonde Ganache',
    '%p32': 'Schoko-Erdnussbutter-Käsekuchen',
    '%p64': 'Schoko-Minze Fudge',
    '%p128': 'Schoko-Spinnennetz',
    '%p256': 'Geröstetes Marshmallow',
    '%p512': 'Kekse & Creme',
    '%p1024': 'Schoko-Sundae',
    '%p2048': 'Weiße Schoko-Pfefferminze',
    '%p4096': '2017 Konfetti Vanille',
    '%p8192': 'Regenbogen'
  },

  "fr": {
    "%game-intro": "Rejoignez les <strong>Cupcakes!</strong>",
    "%restart-button": "Rejouer",
    "%keep-playing-button": "Continuer",
    "%retry-button": "Réessayer",
    "%game-won": "Vous avez gagné !",
    "%game-over": "Partie terminée !",
    "%game-explanation": "<strong class=\"important\">Comment jouer :</strong> Utilisez les <strong>flèches directionnelles</strong> pour déplacer les tuiles. Lorsque deux tuiles identiques se touchent, elles <strong>fusionnent !</strong>",
    "%disclaimer": "",
    "%credits": "Images de cupcakes par <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1": "J'ai marqué \"",
    "%tweet2": " sur 2048-CUPCAKES #2048game",
    "%tile-legend": "<strong class=\"important\">Légende des tuiles :</strong>",
    '%2': 'Gâteau d’anniversaire vanille',
    '%4': 'Rose bubblegum',
    '%8': 'Vanille ensoleillée',
    '%16': 'Ganache blonde Valrhona',
    '%32': 'Cheesecake chocolat beurre de cacahuète',
    '%64': 'Fudge menthe chocolat',
    '%128': 'Toile d’araignée chocolat',
    '%256': 'Guimauve grillée',
    '%512': 'Oréo crème',
    '%1024': 'Sundae chocolat',
    '%2048': 'Chocolat blanc menthe',
    '%4096': 'Vanille confettis 2017',
    '%8192': 'Arc-en-ciel',
    '%p0': 'Gâteau d’anniversaire vanille',
    '%p4': 'Rose bubblegum',
    '%p8': 'Vanille ensoleillée',
    '%p16': 'Ganache blonde Valrhona',
    '%p32': 'Cheesecake chocolat beurre de cacahuète',
    '%p64': 'Fudge menthe chocolat',
    '%p128': 'Toile d’araignée chocolat',
    '%p256': 'Guimauve grillée',
    '%p512': 'Oréo crème',
    '%p1024': 'Sundae chocolat',
    '%p2048': 'Chocolat blanc menthe',
    '%p4096': 'Vanille confettis 2017',
    '%p8192': 'Arc-en-ciel'
  }
}

String.toLocaleString(_localeString);